### ISSUE TITLE
syntax error!

### ISSUE THREAD

**Issue by Indeserpen** [ThomasTJdev/WMD#2]
When running wmd with webinterface every tool i run i get syntax error!!
![screenshot from 2017-01-24 11-58-44](https://cloud.githubusercontent.com/assets/13330266/22242576/8029fa96-e22c-11e6-91a0-cb995b596738.png)

Thanks!

**Comment by ThomasTJdev** [comment]
Hi @Indeserpen 

Thank you for testing and reporting back! 
I hav just tested the following 2 scenarios - no problem here. 

#### Scenario 1
1. python3 wmd.py -w
2. Access: 127.0.0.1:5000
3. Click: ChangeMe
4. xterm opens with module

### Scenario 2
1. python3 wmd.py
2. www
3. Access: 127.0.0.1:5000
4. Click: ChangeMe
5. xterm opens with module

# Information
Would you mind fill out the info below?

### Actual behaviour + Errorcode

Tell us what happens


### Expected behaviour

Tell us what should actually happen


### Steps to reproduce

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. 
Here is an example:

1. sudo wmd.py -nc
2. sm
3. use apsniff


### System information

- OS (ARCH, Debian, etc.):
- Python version:

**Comment by Indeserpen** [comment]
ok i will update today and debug all problem! system i use Kali Rolling 64 bit!

**Comment by Indeserpen** [comment]
scenario 1.

![screenshot from 2017-01-24 23-22-04](https://cloud.githubusercontent.com/assets/13330266/22267296/f23be3d8-e28b-11e6-8902-6a4eb850073d.png)
![screenshot from 2017-01-24 23-21-39](https://cloud.githubusercontent.com/assets/13330266/22267302/f5fa4442-e28b-11e6-8045-35699750f06f.png)

No matter what tool I i use i get this xterm window with syntax errror!


scenario 2:
![screenshot from 2017-01-24 11-58-44](https://cloud.githubusercontent.com/assets/13330266/22267608/185357d0-e28d-11e6-88d9-7a97e44cde66.png)

Like you can see from image same stuff!

Maybe there is something with requirements?
I am not able to install either difflib, or http.client using pip3 either apt!!

**Comment by Indeserpen** [comment]
Tried pip3 install --upgrade -r requirements.txt not working! Difflib sequencer cannot be imported either installed using pip or apt!! 
Python versions installed:
root@kali:~# python --version
Python 2.7.13
root@kali:~# python3 --version
Python 3.5.3rc1
root@kali:~#

**Comment by ThomasTJdev** [comment]
Thanks for the screenshots!

1. I have removed difflib and http.client (httpclient) from requirements.txt in the newest commits. I think it's python standard libraries.
2. I have updated the CSS for the webinterface to avoid the strange rendering of buttons.
3. **It looks like, that your problem is with the banners.** Would you mind trying to change the beautiful banners to "XXX". They can be found in `core/banners.py` and the code you need to change is in `banner1 = """ XXXX """`, `banner2 = """ XXXX """` and `banner3 = """ XXXX """`.

P.S. If you'll pull again, please note that I have changed the name of `core/config.ini` to `core/config.ini.default`. Rename it to `core/config.ini`, then new pulls will avoid changing your user specified config file.

**Comment by ThomasTJdev** [comment]
Missing feedback from user.
