### ISSUE TITLE
ImportError: psutil

### ISSUE THREAD

**Issue by ghost** [ThomasTJdev/WMD#3]
I have psutil installed. i tired providing the path to psutil but am still getting this error. I installed everything that pip could find from the requirements.txt.

Traceback (most recent call last):
  File "wmd.py", line 18, in <module>
    import core.commands as comm
  File "/home/user/WMD/core/commands.py", line 12, in <module>
    import psutil
ImportError: No module named 'psutil'

**Comment by ThomasTJdev** [comment]
Hi @blkv0lk 

That seems strange. Would you mind try running the commands below?
### psutil
```python3
1. blkv0lk: python
2. blkv0lk: import psutil
3. blkv0lk: for s in psutil.net_if_addrs():
4. blkv0lk:     print(s)
```

# System information
Would you mind fill out the info below?

### Actual behaviour + Errorcode

Tell us what happens


### Expected behaviour

Tell us what should actually happen


### Steps to reproduce

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. 
Here is an example:

1. sudo wmd.py -nc
2. sm
3. use apsniff


### System information

- OS (ARCH, Debian, etc.):
- Python version:

**Comment by ThomasTJdev** [comment]
Closed - no feedback
